export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT'
export const SET_SEARCHED_TEXT = 'SET_SEARCHED_TEXT'
export const TOGGLE_SEARCH_LIST = 'TOGGLE_SEARCH_LIST'
export const SET_SELECTED_PRODUCT = 'SET_SELECTED_PRODUCT'
export const SET_RECENT_SEARCHED_PRODUCT = 'SET_RECENT_SEARCHED_PRODUCT'

